### ISSUE TITLE
Flesh out installation/getting started instructions

### ISSUE THREAD

**Issue by FinniganIK** [calum-chamberlain/ESCI451-Python#14]
Depending on exactly how we want them to do it, we should include details about cloning from github and even `jupyter notebook`

**Comment by calum-chamberlain** [comment]
I can't remember how we did it last year, but I'm keen to avoid github for the students altogether. My thinking is that I will make a clean 2022 release of this as a zip file and put that on blackboard so that the students just have to download that.

I also plan on that "release" having no output in the cells so that the students actually have to interact to see the output.

**Comment by FinniganIK** [comment]
Ok nice, that sounds good to me

**Comment by calum-chamberlain** [comment]
Also the intro_slides.ipynb notebook is what I planned on showing first on the big screen which ends with install instructions and starting the notebook - I think it would be a good idea to have a pdf of instructions though, and a basic "how to open your terminal" thing, But we can discuss this in a bit.
